import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/Footer/Footer';
import { ThemeProvider } from "../components/DarkModeToggle/ThemeContext";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DMC',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body >
          <ThemeProvider>
            <Navbar />
            <main>{children}</main>
            <Footer />
          </ThemeProvider>
        </body>
    </html>
  )
}