import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/Footer/Footer';
import { ThemeProvider } from "../context/ThemeContext";
import ToasterContext from "../components/Form/ToasterContext";
import Provider from '@/components/Form/Provider';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DMC',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body >
          <ToasterContext />
          <ThemeProvider>
            <Navbar />
            <Provider>{children}</Provider>
            <Footer />
          </ThemeProvider>
        </body>
    </html>
  )
}