// Source: VCU Bulletin program index, filtered to undergraduate bachelor's programs.
// Update this list when VCU changes its official catalog.
export const vcuMajorOptions = [
  "Accounting, Bachelor of Science (B.S.)",
  "African American Studies, Bachelor of Arts (B.A.)",
  "African American Studies, Bachelor of Arts (B.A.) with a concentration in artistic, historical and literary perspectives",
  "African American Studies, Bachelor of Arts (B.A.) with a concentration in education",
  "African American Studies, Bachelor of Arts (B.A.) with a concentration in political, religious and societal perspectives",
  "African American Studies, Bachelor of Arts (B.A.) with a concentration in public administration",
  "African American Studies, Bachelor of Arts (B.A.) with a concentration in social and behavioral perspectives",
  "Anthropology, Bachelor of Science (B.S.)",
  "Art History, Bachelor of Arts (B.A.)",
  "Arts, Bachelor of Fine Arts (B.F.A.) with a concentration in art education",
  "Bioinformatics, Bachelor of Science (B.S.) with a concentration in biological/genomic sciences",
  "Bioinformatics, Bachelor of Science (B.S.) with a concentration in computational sciences",
  "Bioinformatics, Bachelor of Science (B.S.) with a concentration in quantitative/statistical sciences",
  "Biology, Bachelor of Science (B.S.)",
  "Biomedical Engineering, Bachelor of Science (B.S.)",
  "Business, Bachelor of Science (B.S.) with a concentration in human resource management",
  "Business, Bachelor of Science (B.S.) with a concentration in management/business administration",
  "Business, Bachelor of Science (B.S.) with a concentration in management/entrepreneurship",
  "Business, Bachelor of Science (B.S.) with a concentration in management/international management",
  "Business, Bachelor of Science (B.S.) with a concentration in risk management and insurance",
  "Business, Bachelor of Science (B.S.) with a concentration in supply chain management and analytics",
  "Chemical and Life Science Engineering, Bachelor of Science (B.S.) with a concentration in chemical engineering",
  "Chemical and Life Science Engineering, Bachelor of Science (B.S.) with a concentration in life science engineering",
  "Chemistry, Bachelor of Science (B.S.) with a concentration in biochemistry",
  "Chemistry, Bachelor of Science (B.S.) with a concentration in chemical modeling",
  "Chemistry, Bachelor of Science (B.S.) with a concentration in chemical science",
  "Chemistry, Bachelor of Science (B.S.) with a concentration in professional chemist",
  "Chemistry, Bachelor of Science (B.S.) with a concentration in professional chemist with honors",
  "Cinema, Bachelor of Arts (B.A.)",
  "Clinical Radiation Sciences, Bachelor of Science (B.S.) with a concentration in diagnostic medical sonography",
  "Clinical Radiation Sciences, Bachelor of Science (B.S.) with a concentration in diagnostic medical sonography (second modality)",
  "Clinical Radiation Sciences, Bachelor of Science (B.S.) with a concentration in nuclear medicine technology",
  "Clinical Radiation Sciences, Bachelor of Science (B.S.) with a concentration in nuclear medicine technology (degree completion)",
  "Clinical Radiation Sciences, Bachelor of Science (B.S.) with a concentration in nuclear medicine technology (second modality)",
  "Clinical Radiation Sciences, Bachelor of Science (B.S.) with a concentration in radiation therapy",
  "Clinical Radiation Sciences, Bachelor of Science (B.S.) with a concentration in radiation therapy (degree completion)",
  "Clinical Radiation Sciences, Bachelor of Science (B.S.) with a concentration in radiation therapy (second modality)",
  "Clinical Radiation Sciences, Bachelor of Science (B.S.) with a concentration in radiography",
  "Clinical Radiation Sciences, Bachelor of Science (B.S.) with a concentration in radiography (degree completion)",
  "Communication Arts, Bachelor of Fine Arts (B.F.A.)",
  "Communication Arts, Bachelor of Fine Arts (B.F.A.) with a concentration in scientific illustration",
  "Communication Arts, Bachelor of Fine Arts (B.F.A.) with a concentration in visual effects",
  "Computer Engineering, Bachelor of Science (B.S.)",
  "Computer Engineering, Bachelor of Science (B.S.) with a concentration in autonomy and artificial intelligence",
  "Computer Engineering, Bachelor of Science (B.S.) with a concentration in digital hardware design",
  "Computer Science, Bachelor of Arts (B.A.)",
  "Computer Science, Bachelor of Science (B.S.)",
  "Computer Science, Bachelor of Science (B.S.) with a concentration in cybersecurity",
  "Computer Science, Bachelor of Science (B.S.) with a concentration in data science",
  "Computer Science, Bachelor of Science (B.S.) with a concentration in software engineering",
  "Craft and Material Studies, Bachelor of Fine Arts (B.F.A.)",
  "Criminal Justice, Bachelor of Science (B.S.)",
  "Criminal Justice, Bachelor of Science (B.S.) with a concentration in forensic crime scene investigation",
  "Dance and Choreography, Bachelor of Fine Arts (B.F.A.)",
  "Dental Hygiene, Bachelor of Science (B.S.)",
  "Early Childhood Education and Teaching, Bachelor of Science in Education (B.S.Ed.)",
  "Economics, Bachelor of Science (B.S.) [College of Humanities and Sciences]",
  "Economics, Bachelor of Science (B.S.) [School of Business]",
  "Electrical Engineering, Bachelor of Science (B.S.)",
  "Electrical Engineering, Bachelor of Science (B.S.) with a concentration in power and energy systems",
  "Elementary Education and Teaching, Bachelor of Science in Education (B.S.Ed.)",
  "English, Bachelor of Arts (B.A.)",
  "Environmental Studies, Bachelor of Science (B.S.)",
  "Fashion, Bachelor of Arts (B.A.) with a concentration in fashion merchandising",
  "Fashion, Bachelor of Fine Arts (B.F.A.) with a concentration in fashion design",
  "Finance, Bachelor of Science (B.S.)",
  "Finance, Bachelor of Science (B.S.) with a concentration in actuarial science",
  "Finance, Bachelor of Science (B.S.) with a concentration in financial planning",
  "Finance, Bachelor of Science (B.S.) with a concentration in risk management and insurance",
  "Financial Technology, Bachelor of Science (B.S.) with a concentration in actuarial science",
  "Financial Technology, Bachelor of Science (B.S.) with a concentration in financial engineering",
  "Foreign Language, Bachelor of Arts (B.A.) with a concentration in dual languages",
  "Foreign Language, Bachelor of Arts (B.A.) with a concentration in French",
  "Foreign Language, Bachelor of Arts (B.A.) with a concentration in German",
  "Foreign Language, Bachelor of Arts (B.A.) with a concentration in Spanish",
  "Forensic Science, Bachelor of Science (B.S.) with a concentration in forensic biology",
  "Forensic Science, Bachelor of Science (B.S.) with a concentration in forensic chemistry",
  "Forensic Science, Bachelor of Science (B.S.) with a concentration in physical evidence",
  "Gender, Sexuality and Women's Studies, Bachelor of Arts (B.A.)",
  "Gender, Sexuality and Women's Studies, Bachelor of Arts (B.A.) with a concentration in health, society and social justice",
  "Gender, Sexuality and Women's Studies, Bachelor of Arts (B.A.) with a concentration in LGBT+ and Queer studies",
  "Graphic Design, Bachelor of Fine Arts (B.F.A.)",
  "Health and Physical Education, Bachelor of Science in Education (B.S.Ed.)",
  "Health Services, Bachelor of Science (B.S.)",
  "Health, Physical Education and Exercise Science, Bachelor of Science (B.S.) with a concentration in exercise science",
  "Health, Physical Education and Exercise Science, Bachelor of Science (B.S.) with a concentration in health science",
  "History, Bachelor of Arts (B.A.)",
  "History, Bachelor of Arts (B.A.) with a concentration in public history",
  "Homeland Security and Emergency Preparedness, Bachelor of Arts (B.A.)",
  "Human and Organizational Development, Bachelor of Arts (B.A.)",
  "Information Systems, Bachelor of Science (B.S.)",
  "Interdisciplinary Studies, Bachelor of (B.I.S.) [University College]",
  "Interdisciplinary Studies, Bachelor of (B.I.S.) with a liberal studies for early and elementary education major [College of Humanities and Sciences]",
  "Interior Design, Bachelor of Fine Arts (B.F.A.)",
  "International Studies, Bachelor of Arts (B.A.) with a concentration in European studies",
  "International Studies, Bachelor of Arts (B.A.) with a concentration in general studies",
  "International Studies, Bachelor of Arts (B.A.) with a concentration in global religions and spiritualities",
  "International Studies, Bachelor of Arts (B.A.) with a concentration in international social justice studies",
  "International Studies, Bachelor of Arts (B.A.) with a concentration in Latin American studies",
  "International Studies, Bachelor of Arts (B.A.) with a concentration in world cinema",
  "Kinetic Imaging, Bachelor of Fine Arts (B.F.A.)",
  "Marketing, Bachelor of Science (B.S.) with a concentration in general marketing",
  "Marketing, Bachelor of Science (B.S.) with a concentration in marketing communication and analytics",
  "Marketing, Bachelor of Science (B.S.) with a concentration in personal selling and business marketing",
  "Marketing, Bachelor of Science (B.S.) with a concentration in product and brand management",
  "Mass Communications, Bachelor of Science (B.S.) with a concentration in advertising/creative",
  "Mass Communications, Bachelor of Science (B.S.) with a concentration in advertising/strategic",
  "Mass Communications, Bachelor of Science (B.S.) with a concentration in journalism",
  "Mass Communications, Bachelor of Science (B.S.) with a concentration in journalism/broadcast",
  "Mass Communications, Bachelor of Science (B.S.) with a concentration in journalism/digital",
  "Mass Communications, Bachelor of Science (B.S.) with a concentration in media production",
  "Mass Communications, Bachelor of Science (B.S.) with a concentration in public relations",
  "Mathematical Sciences, Bachelor of Science (B.S.) with a concentration in applied mathematics",
  "Mathematical Sciences, Bachelor of Science (B.S.) with a concentration in biomathematics",
  "Mathematical Sciences, Bachelor of Science (B.S.) with a concentration in general mathematical sciences",
  "Mathematical Sciences, Bachelor of Science (B.S.) with a concentration in mathematics",
  "Mathematical Sciences, Bachelor of Science (B.S.) with a concentration in operations research",
  "Mathematical Sciences, Bachelor of Science (B.S.) with a concentration in secondary teacher preparation",
  "Mathematical Sciences, Bachelor of Science (B.S.) with a concentration in statistics",
  "Mechanical Engineering, Bachelor of Science (B.S.)",
  "Mechanical Engineering, Bachelor of Science (B.S.) with a concentration in nuclear engineering",
  "Medical Laboratory Sciences, Bachelor of Science (B.S.)",
  "Music, Bachelor of (B.M.) with a concentration in music education/instrumental",
  "Music, Bachelor of (B.M.) with a concentration in music education/vocal-choral",
  "Music, Bachelor of (B.M.) with a concentration in performance/guitar",
  "Music, Bachelor of (B.M.) with a concentration in performance/jazz",
  "Music, Bachelor of (B.M.) with a concentration in performance/piano",
  "Music, Bachelor of (B.M.) with a concentration in performance/strings",
  "Music, Bachelor of (B.M.) with a concentration in performance/voice",
  "Music, Bachelor of (B.M.) with a concentration in performance/winds and percussion",
  "Music, Bachelor of Arts (B.A.)",
  "Music, Bachelor of Arts (B.A.) with a concentration in media scoring",
  "Nursing, Bachelor of Science (B.S.)",
  "Nursing, Bachelor of Science (B.S.), R.N.-B.S. completion program",
  "Painting and Printmaking, Bachelor of Fine Arts (B.F.A.)",
  "Pharmaceutical Sciences, Bachelor of Science (B.S.)",
  "Philosophy, Bachelor of Arts (B.A.)",
  "Philosophy, Bachelor of Arts (B.A.) with a concentration in ethics and philosophy of AI",
  "Philosophy, Bachelor of Arts (B.A.) with a concentration in ethics and public policy",
  "Philosophy, Bachelor of Arts (B.A.) with a concentration in philosophy and law",
  "Philosophy, Bachelor of Arts (B.A.) with a concentration in philosophy and science",
  "Photography and Film, Bachelor of Fine Arts (B.F.A) with a concentration in filmmaking",
  "Photography and Film, Bachelor of Fine Arts (B.F.A) with a concentration in photography",
  "Physics, Bachelor of Science (B.S.)",
  "Physics, Bachelor of Science (B.S.) with a concentration in nanoscience",
  "Physics, Bachelor of Science (B.S.) with a concentration in pre-medical",
  "Political Science, Bachelor of Arts (B.A.)",
  "Political Science, Bachelor of Arts (B.A.) with a concentration in civil rights",
  "Political Science, Bachelor of Arts (B.A.) with a concentration in comparative politics",
  "Political Science, Bachelor of Arts (B.A.) with a concentration in human security",
  "Political Science, Bachelor of Arts (B.A.) with a concentration in international relations",
  "Political Science, Bachelor of Arts (B.A.) with a concentration in political theory and methodology",
  "Political Science, Bachelor of Arts (B.A.) with a concentration in politics and government",
  "Political Science, Bachelor of Arts (B.A.) with a concentration in public policy and administration",
  "Political Science, Bachelor of Arts (B.A.) with a concentration in U.S. government",
  "Psychology, Bachelor of Science (B.S.)",
  "Psychology, Bachelor of Science (B.S.) with a concentration in addiction studies",
  "Psychology, Bachelor of Science (B.S.) with a concentration in applied psychology",
  "Psychology, Bachelor of Science (B.S.) with a concentration in life science",
  "Psychology, Bachelor of Science (B.S.) with a concentration in pre-graduate school",
  "Psychology, Bachelor of Science (B.S.) with a concentration in urban psychology",
  "Real Estate, Bachelor of Science (B.S.)",
  "Religious Studies, Bachelor of Arts (B.A.)",
  "Robotics and Autonomous Systems Engineering, Bachelor of Science (B.S.)",
  "Science, Bachelor of Science (B.S.) with a concentration in biology",
  "Science, Bachelor of Science (B.S.) with a concentration in chemistry",
  "Science, Bachelor of Science (B.S.) with a concentration in physics",
  "Science, Bachelor of Science (B.S.) with a concentration in professional science",
  "Sculpture, Bachelor of Fine Arts (B.F.A.)",
  "Secondary Education and Teaching, Bachelor of Science in Education (B.S.Ed.) with a concentration in engineering education",
  "Secondary Education and Teaching, Bachelor of Science in Education (B.S.Ed.) with a concentration in English education",
  "Secondary Education and Teaching, Bachelor of Science in Education (B.S.Ed.) with a concentration in history education",
  "Secondary Education and Teaching, Bachelor of Science in Education (B.S.Ed.) with a concentration in math education",
  "Social Work, Bachelor of (B.S.W.)",
  "Sociology, Bachelor of Science (B.S.)",
  "Special Education and Teaching, Bachelor of Science in Education (B.S.Ed.)",
  "Special Education and Teaching, Bachelor of Science in Education (B.S.Ed.) with a concentration in early childhood",
  "Supply Chain Management, Bachelor of Science (B.S.)",
  "Theatre, Bachelor of Arts (B.A.)",
  "Theatre, Bachelor of Fine Arts (B.F.A.) with a concentration in costume design/technical production",
  "Theatre, Bachelor of Fine Arts (B.F.A.) with a concentration in lighting design/technical production",
  "Theatre, Bachelor of Fine Arts (B.F.A.) with a concentration in performance",
  "Theatre, Bachelor of Fine Arts (B.F.A.) with a concentration in performance/musical theatre",
  "Theatre, Bachelor of Fine Arts (B.F.A.) with a concentration in scene design/technical production",
  "Theatre, Bachelor of Fine Arts (B.F.A.) with a concentration in stage management/technical production",
  "Urban and Regional Studies, Bachelor of Science (B.S.)",
  "Undeclared",
];
