// Source: VCU Bulletin program index, filtered to official minor programs.
// Update this list when VCU changes its official catalog.
export const vcuMinorOptions = [
  "Actuarial science, minor in",
  "Aerospace engineering, minor in",
  "African American studies, minor in",
  "AI studies in humanities and sciences, minor in",
  "American studies, minor in",
  "Animation, minor in",
  "Anthropology, minor in",
  "Applied humanities, minor in",
  "Art history, minor in",
  "Artificial intelligence, minor in",
  "Biology, minor in",
  "Biomedical engineering, minor in",
  "British studies, minor in",
  "Business analytics, minor in",
  "Chemical and life science engineering, minor in",
  "Chemistry, minor in",
  "Community mental health services, minor in",
  "Computer engineering, minor in",
  "Computer science, minor in",
  "Craft and material studies, minor in",
  "Creative technology instruction, minor in",
  "Creative writing, minor in",
  "Criminal justice, minor in",
  "Cybersecurity, minor in",
  "Dance and choreography, minor in",
  "Data science, minor in",
  "Dental administration, minor in",
  "Early intervention and early childhood special education, minor in",
  "Economics, minor in",
  "Education, minor in",
  "Electrical engineering, minor in",
  "English, minor in",
  "Entrepreneurship, minor in",
  "Environmental and sustainable engineering, minor in",
  "Environmental studies, minor in",
  "European studies, minor in",
  "Fashion merchandising, minor in",
  "Finance, minor in",
  "French studies, minor in",
  "French, minor in",
  "Gender, sexuality and women's studies, minor in",
  "General business, minor in",
  "German studies, minor in",
  "Global environmental humanities, minor in",
  "Health communication, minor in",
  "Health education, minor in",
  "Health humanities, minor in",
  "Health sciences, minor in",
  "Health services, minor in",
  "Healthcare change leadership, minor in",
  "History of science, technology and medicine, minor in",
  "History, minor in",
  "Homeland security and emergency preparedness, minor in",
  "Human resource management, minor in",
  "Information systems, minor in",
  "Instructional design and technology, minor in",
  "International social justice studies, minor in",
  "Italian studies, minor in",
  "Latin American studies, minor in",
  "LGBT+ and queer studies, minor in",
  "Management, minor in",
  "Marketing insights, minor in",
  "Mathematics, minor in",
  "Mechanical engineering, minor in",
  "Media studies, minor in",
  "Mental health, wellness and counseling, minor in",
  "Middle Eastern and Islamic studies, minor in",
  "Military science and leadership, minor in",
  "Mixed and immersive reality studies, minor in",
  "Music, minor in",
  "Musical theatre, minor in",
  "Native American and Indigenous studies, minor in",
  "Nonprofit management and administration, minor in",
  "Nuclear engineering, minor in",
  "Painting and printmaking, minor in",
  "Philosophy of law, minor in",
  "Philosophy, minor in",
  "Physics, minor in",
  "Political science, minor in",
  "Practical AI, minor in",
  "Pre-dentistry, minor in",
  "Pre-medicine, minor in",
  "Pre-occupational therapy, minor in",
  "Pre-optometry, minor in",
  "Pre-pharmacy, minor in",
  "Pre-physical therapy, minor in",
  "Pre-physician assistant, minor in",
  "Pre-veterinary medicine, minor in",
  "Professional writing and editing, minor in",
  "Psychology, minor in",
  "Public health and arts, minor in",
  "Public health, minor in",
  "Public management, minor in",
  "Real estate, minor in",
  "Recreation and wellness, minor in",
  "Regenerative medicine, minor in",
  "Religious studies, minor in",
  "Research ecosystems, minor in",
  "Risk management and insurance, minor in",
  "Robotics, minor in",
  "Russian studies, minor in",
  "Sales, minor in",
  "Scientific illustration, minor in",
  "Screenwriting, minor in",
  "Sculpture, minor in",
  "Social welfare, minor in",
  "Social work and mental health, minor in",
  "Sociology, minor in",
  "Software engineering, minor in",
  "Sound design, minor in",
  "Spanish and health sciences, minor in",
  "Spanish, minor in",
  "Special education, minor in",
  "Sport and fitness management, minor in",
  "Statistics, minor in",
  "Teacher preparation for historians, minor in",
  "Teaching English to speakers of other languages, minor in",
  "Theatre, minor in",
  "Urban and regional studies, minor in",
  "Visual effects, minor in",
  "World cinema, minor in",
  "No minor",
];
