version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_Signin_URI: ${{ secrets.MONGODB_Signin_URI }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
    paths:
      - node_modules/**/*