name: Deploy Application

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository
    - uses: actions/checkout@v2

    # 2. Clean up runner disk before anything else
    - name: Pre-build cleanup
      run: |
        echo "Cleaning up temporary files..."
        sudo rm -rf /tmp/*
        sudo rm -rf backend/node_modules
        sudo rm -rf frontend/node_modules
        docker system prune -af || true
        echo "Disk usage after cleanup:"
        df -h

    # 3. Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    # 4. Increase Node memory for Next.js
    - name: Set Node memory limit
      run: |
        export NODE_OPTIONS="--max-old-space-size=4096"
        echo "Node memory limit set to 4GB"

    # 5. Debug Backend Directory (Optional)
    - name: Debug Backend Folder
      run: |
        echo "Checking backend folder contents..."
        cd backend
        ls -la

    # 6. Install Backend Dependencies (Strapi)
    - name: Install Backend Dependencies
      run: |
        cd backend
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    # 7. Build Backend (Strapi)
    - name: Build Backend
      run: |
        cd backend
        npm run build

    # 8. Debug Frontend Directory (Optional)
    - name: Debug Frontend Folder
      run: |
        echo "Checking frontend folder contents..."
        cd frontend
        ls -la

    # 9. Install Frontend Dependencies (Next.js)
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    # 10. Build Frontend (Next.js) with debug
    - name: Build Frontend
      run: |
        cd frontend
        npx next build --debug
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        MONGODB_Signin_URI: ${{ secrets.MONGODB_Signin_URI }}
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_PAYMENT_DESCRIPTION: ${{ secrets.STRIPE_PAYMENT_DESCRIPTION }}
        STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
