name: Deploy Application

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository
    - uses: actions/checkout@v2

    # 2. Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    # 3. Debug Backend Directory (Optional)
    - name: Debug Backend Folder
      run: |
        echo "Checking backend folder contents..."
        cd backend
        ls -la

    # 4. Install Backend Dependencies (Strapi)
    - name: Install Backend Dependencies
      run: |
        cd backend
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    # 5. Build Backend (Strapi)
    - name: Build Backend
      run: |
        cd backend
        npm run build

    # 6. Debug Frontend Directory (Optional)
    - name: Debug Frontend Folder
      run: |
        echo "Checking frontend folder contents..."
        cd frontend
        ls -la

    # 7. Install Frontend Dependencies (Next.js)
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    # 8. Build Frontend (Next.js)
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        MONGODB_Signin_URI: ${{ secrets.MONGODB_Signin_URI }}
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_PAYMENT_DESCRIPTION: ${{ secrets.STRIPE_PAYMENT_DESCRIPTION }}
        STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}

    # 🧹 9. Clean up disk space to prevent "No space left on device" errors
    - name: Clean up disk space
      run: |
        echo "Cleaning up..."
        sudo rm -rf /tmp/*
        sudo rm -rf ${{ github.workspace }}/backend/node_modules
        sudo rm -rf ${{ github.workspace }}/frontend/node_modules
        docker system prune -af || true
        echo "Disk space after cleanup:"
        df -h

        
